// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzgmVRG_8AvbQcUIs8OojNQIBb4u_oYE',
    appId: '1:286978817451:android:c78d177844d951909f66ee',
    messagingSenderId: '286978817451',
    projectId: 'edutest-351231',
    databaseURL: 'https://edutest-351231-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutest-351231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8ZfEAYs1MY8MovGkUM4kk9F3zoYHdqE',
    appId: '1:286978817451:ios:4c295779ffc00cb29f66ee',
    messagingSenderId: '286978817451',
    projectId: 'edutest-351231',
    databaseURL: 'https://edutest-351231-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'edutest-351231.firebasestorage.app',
    androidClientId: '286978817451-ihanpq7easr4en32narp6qremtcrglmt.apps.googleusercontent.com',
    iosClientId: '286978817451-ej3vd7av1gs7r64parrjae65dd3upg5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.edutest',
  );

}